DOCSP-12575: kms azure python updates
mongodb-university/csfle-guides pull request #13
Opened 2020-11-04 17:12 UTC by ccho-mongodb

JIRA:
https://jira.mongodb.org/browse/DOCSP-12575

No assets to stage

2020-11-05 16:53 UTC, terakilobyte requested changes
small things I noticed

2020-11-05 16:53 UTC, terakilobyte commented on python/app.py
> +    keyNamespace = f"{keyDb}.{keyColl}"
this ends up not being used

2020-11-06 19:49 UTC, ccho-mongodb commented on python/app.py
> +    """
Hm, I think this was intentional, but is missing the actual AWS KMS code. Will fill in.

2020-11-09 14:48 UTC, terakilobyte approved these changes
lgtm

2020-11-09 15:55 UTC, merged